### ISSUE TITLE
Error in cg_extract_solutions for 7 variable system

### ISSUE THREAD

**Issue by rakshith95** [prclibo/gaps#4]
Hello, 
I have a system with 7 variables, and on Mcaulay2, I can generate a zero dim Ideal from it. However, when I run the `generate_solver.m` function, I get the error:
```
Error using assert
Assertion failed.

Error in cg_extract_solutions (line 7)
assert(numel(unk_vars) == numel(scheme)); 
```

Full trace:
```
Problem Config:
    rand_seed: 23


in = 

  struct with fields:

    a_3: a_3
    a_4: a_4
    u_1: u_1


in = 

  struct with fields:

    a_3: a_3
    a_4: a_4
    u_1: u_1
    u_2: u_2


in = 

  struct with fields:

    a_3: a_3
    a_4: a_4
    u_1: u_1
    u_2: u_2
    u_3: u_3


in = 

  struct with fields:

    a_3: a_3
    a_4: a_4
    u_1: u_1
    u_2: u_2
    u_3: u_3
    u_4: u_4


in = 

  struct with fields:

    a_3: a_3
    a_4: a_4
    u_1: u_1


in = 

  struct with fields:

    a_3: a_3
    a_4: a_4
    u_1: u_1
    u_2: u_2


in = 

  struct with fields:

    a_3: a_3
    a_4: a_4
    u_1: u_1
    u_2: u_2
    u_3: u_3


in = 

  struct with fields:

    a_3: a_3
    a_4: a_4
    u_1: u_1
    u_2: u_2
    u_3: u_3
    u_4: u_4

Sampling Zp instances
...In total 8 terms
...Evaluating instances for          8
Elapsed time is 0.841998 seconds.
-- Sampled.
-------------------------------------------------
generate_solverChecking for symmetry. max_p = 2
Elapsed time is 1.300600 seconds.
-- Found 0 symmetries.
./cache/find_monomial_basis.solver_VLVP_problem_woA.1.m2
Macaulay2, version 1.21
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems,
               Isomorphism, LLLBases, MinimalPrimes, OnlineLookup,
               PrimaryDecomposition, ReesAlgebra, Saturation, TangentCone
Problem has (at most) 1 solutions.
Quotient ring basis (degree = 1)
	B = [ 1 ]
Action monomial = [ a_1 a_2 v_1 v_2 v_3 l_1 l_2 ]
Elapsed time is 0.134153 seconds.
Monomials to reduce: (7 monomials)
	R = [ a_1, a_2, v_1, v_2, v_3, l_1, l_2 ]
Finding elimination templates ... ./cache/find_template.solver_VLVP_problem_woA.1.m2
Macaulay2, version 1.21
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems,
               Isomorphism, LLLBases, MinimalPrimes, OnlineLookup,
               PrimaryDecomposition, ReesAlgebra, Saturation, TangentCone
OK
Found 7 elimination templates.
  action_a_1  -  49  rows,  1 basis,  1 reducible, 
  action_a_2  -  47  rows,  1 basis,  1 reducible, 
* action_v_1  -  23  rows,  1 basis,  1 reducible, 
  action_v_2  -  23  rows,  1 basis,  1 reducible, 
  action_v_3  -  23  rows,  1 basis,  1 reducible, 
  action_l_1  -  48  rows,  1 basis,  1 reducible, 
  action_l_2  -  48  rows,  1 basis,  1 reducible, 
Extracting template coefficients... OK (47 found)
Building solver (solver_VLVP_problem_woA_action_v_1)
Warning: unable to extract: x1 x2 x4 x5 x6 x7  
> In find_extraction_scheme>extract_variables (line 142)
In find_extraction_scheme (line 30)
In finalize_template (line 7)
In generate_solver (line 199) 
Elimination template size = [23,38], nnz = 136
Error using assert
Assertion failed.

Error in cg_extract_solutions (line 7)
assert(numel(unk_vars) == numel(scheme));

Error in generate_code (line 36)
str = [str cg_extract_solutions(solv,template,opt)];

Error in generate_solver (line 219)
        solv.templates{tk} = generate_code(name,solv,solv.templates{tk},opt);
```

Do you have an idea on why this happens? 

For reference, the Mcaulay2 code:

```
load "EigenSolver.m2"
gbTrace = 3

R = QQ[l_1..l_2, v_1..v_3,a_1..a_4,u_1..u_4]
vars R
-- -- Ideal with all a, and u as variables
I = ideal(-l_1*v_3*a_1*u_1-l_2*v_3*a_1*u_2-l_1*v_3*u_3+l_1*v_1-v_3*a_1-a_1+1,-l_1*v_3*a_2*u_1-l_2*v_3*a_2*u_2-l_1*v_3*u_4+l_1*v_2-v_3*a_2-a_2,-l_1*v_3*a_3*u_1-l_2*v_3*a_3*u_2-l_2*v_3*u_3+l_2*v_1-v_3*a_3-a_3,-l_1*v_3*a_4*u_1-l_2*v_3*a_4*u_2-l_2*v_3*u_4+l_2*v_2-v_3*a_4-a_4+1,l_1*v_1+l_2*v_2+v_3,l_1*v_2*u_1+(l_2*v_2+1)*u_2+v_2-(l_1*v_3*u_1+l_2*v_3*u_2+v_3+1)*u_4,-(l_1*v_1+1)*u_1-l_2*v_1*u_2-v_1+(l_1*v_3*u_1+l_2*v_3*u_2+v_3+1)*u_3,((l_1*v_1+1)*u_1+l_2*v_1*u_2+v_1)*u_4-(l_1*v_2*u_1+(l_2*v_2+1)*u_2+v_2)*u_3)
dim I, degree I -- (6,105)

r1 = flatten entries random(R^1, R^6)
s1 = apply(toList(a_1,a_2,u_1,u_2,u_3,u_4), r1, (x,v)->x=>v)
R2 = QQ[l_1..l_2, v_1..v_3,a_3..a_4]
J = sub(sub(I, s1),R2)
dim J, degree J -- (0,1)
S = flatten apply(zeroDimSolve(J),x->x.Coordinates)
netList {flatten entries vars R2, S}

```

I've also attached my <problem>.m code
[VLVP_problem_woA.txt](https://github.com/prclibo/gaps/files/10519799/VLVP_problem_woA.txt)

**Comment by prclibo** [comment]
Hi, there are two possible directions to check:

1. Your rand_arg_zp produces arbitrarily random values. This might not be right if there exists constraints between your input variables. For example, an input quaternion q=[u1, u2, u3, u4] should guarantee that norm(q) == 1 on Z_p. See prob_pc_relpose_4pra_sir2__example for an example, if there exists constraints between your input variables.
2. If you did not make above mistakes, `Quotient ring basis (degree = 1)	B = [ 1 ]` implies that there is probably only one linear solution. The code generation functionality is not adapted to linear systems. But I think you can just comment the assertion. The generator should be able to generate some code and you can modify it manually to extract your solutions.

**Comment by rakshith95** [comment]
Hello @prclibo ,

> Your rand_arg_zp produces arbitrarily random values. This might not be right if there exists constraints between your input variables.

This is not the case with my input variables in the program whose file I've attached.  I also tried giving non-random (integer) values, for which I know there exists a solution, but I encountered the same error.

> If you did not make above mistakes, Quotient ring basis (degree = 1)	B = [ 1 ] implies that there is probably only one linear solution. The code generation functionality is not adapted to linear systems. But I think you can just comment the assertion. 

I think this is indeed the case with my problem, so I will comment out the assertion and see how the resulting solver is.

> . The generator should be able to generate some code and you can modify it manually to extract your solutions.

I'm not sure what you mean by manually modifying it. Could you elaborate a bit on this?

**Comment by hilibo** [comment]
> Hello @prclibo ,
> 
> > Your rand_arg_zp produces arbitrarily random values. This might not be right if there exists constraints between your input variables.
> 
> This is not the case with my input variables in the program whose file I've attached. I also tried giving non-random (integer) values, for which I know there exists a solution, but I encountered the same error.

You should always generate valid Zp samples (either random or designed) with existing solutions, random invalid samples will mislead the generator.

> 
> > If you did not make above mistakes, Quotient ring basis (degree = 1)	B = [ 1 ] implies that there is probably only one linear solution. The code generation functionality is not adapted to linear systems. But I think you can just comment the assertion.
> 
> I think this is indeed the case with my problem, so I will comment out the assertion and see how the resulting solver is.
> 
> > . The generator should be able to generate some code and you can modify it manually to extract your solutions.
> 
> I'm not sure what you mean by manually modifying it. Could you elaborate a bit on this?

You obtain one scheme, corresponding to one unknown variable. The generated code should be able to solve this variable as eigenvalues and you can solve the rest manually.

**Comment by rakshith95** [comment]
>> I also tried giving non-random (integer) values, for which I know there exists a solution,

> You should always generate valid Zp samples (either random or designed) with existing solutions, random invalid samples will mislead the generator.

Yes, sorry, what I meant was I gave some integer values, for which I knew the solution.

> You obtain one scheme, corresponding to one unknown variable. The generated code should be able to solve this variable as eigenvalues and you can solve the rest manually.

Alright, thank you. I will try this out tomorrow and update here.

**Comment by rakshith95** [comment]
@prclibo @hilibo,
I commented out the assertion, and there is some code generated, and it solves for one variable like you said. Is it possible to recover the monomials which correspond to the columns of the C0 matrix?  That would help me recover the variables.

**Comment by prclibo** [comment]
The code is written too long time ago. I forgot too much details. I suspect for linear system, the bottom of the last column of C0\C1 might have all the solved unknowns. Could you check it and let me know the result?

**Comment by rakshith95** [comment]
C0\C1 does not give me a meaningful result, but I'm able to recover three variables from the last three rows of  `rref([C0 C1)`, and recover the remaining by backsubstituting in my original equations.

However, this does not work in all cases, and to understand why it would be helpful if I could recover the monomials that the columns of `C0` correspond to.

EDIT: 

> C0\C1 does not give me a meaningful result,

I think was for some degenerate data (row rank deficient C0), because it gives the right solutions usually for `C0\-C1`

**Comment by prclibo** [comment]
> C0\C1 does not give me a meaningful result, but I'm able to recover three variables from the last three rows of `rref([C0 C1)`, and recover the remaining by backsubstituting in my original equations.
> 
> However, this does not work in all cases, and to understand why it would be helpful if I could recover the monomials that the columns of `C0` correspond to.
> 
> EDIT:
> 
> > C0\C1 does not give me a meaningful result,
> 
> I think was for some degenerate data (row rank deficient C0), because it gives the right solutions usually for `C0\-C1`

Good to know that rref helps. I think it is better to generate a simpler naive linear system to check the generator first as your problem is kinda complex.

In `finalize_template.m`, there is a `templ.mm` which I think should correspond to the full monomials of [C0, C1]. Please check if you can extract via it.

**Comment by hilibo** [comment]
@rakshith95 does the approach work on your linear system?

**Comment by rakshith95** [comment]
Hello, I didn't try extracting the monomials, but I was able to recover the variables from the template, through some trial and error into guessing what the monomials were.
